### ISSUE TITLE
Remove info.connection

### ISSUE THREAD

**Issue by mcm1957** [MyHomeMyData/ioBroker.flexcharts#34]
As flexcharts no longer has a running process, state info.connection should be removed from io-package.json (and manually deleted from older installations)
 
https://github.com/MyHomeMyData/ioBroker.flexcharts/blob/c9d104513a6c7e4d9b11fae68118518bfe24fbeb/io-package.json#L180

As the adapter does not connect / disconnect to any device, info.connection will never be useful 

In addition the following line must be removed:

https://github.com/MyHomeMyData/ioBroker.flexcharts/blob/c9d104513a6c7e4d9b11fae68118518bfe24fbeb/lib/web.js#L36C1-L36C62 

as setState will change staes of web.0 (!). flexstart is NO extra instance, so all instance related routines operate on web.0 - which is definitly not desired.

**Comment by MyHomeMyData** [comment]
@mcm1957 I applied changes to fix issues #33 and #34. Now new error messages came up at adapter check:

  [E114] No adapter are allowed in the repo without admin support (set "common.noConfig = true" and "common.adminUI.config = none" if adapter has no configuration)
  [E166] Unknown type found in io-package.json
  [E143] No main found in the package.json
  [E402] Types of adapter in latest repository and in io-package.json are different "visualization" !== "visualization-widgets"

[E114] Both is present in io-package.json
[E402] is not true, I didn't change the type.
Adapter works fine and I don't know how to solve this.

**Comment by mcm1957** [comment]
I'll check it

**Comment by mcm1957** [comment]
There are two open issues, see
https://github.com/MyHomeMyData/ioBroker.flexcharts/issues/35

- [E402] Types of adapter in latest repository and in [io-package.json](https://github.com/MyHomeMyData/ioBroker.flexcharts/blob/master/io-package.json) are different "visualization" !== "visualization-widgets"

can be ignored for now, I'll adapt at repository file

- [W184] "common.noConfig" is deprecated for admin >= 5 at [io-package.json](https://github.com/MyHomeMyData/ioBroker.flexcharts/blob/master/io-package.json). Please use property "adminUI.config":"none".

common.noConfig is no longer used, so you may remove it.

----

I cannot confirm the messages listed above. I assume you used the web beased checker at www.iobroker.dev. This check is outdated / uses old rules which are no longer valid. Please use iobroker-bot or commandline version of checker https://github.com/ioBroker/ioBroker.repochecker?tab=readme-ov-file#how-to-test-via-cli
