### ISSUE TITLE
Angezeigte Fehler / Warnungen

### ISSUE THREAD

**Issue by mcuiobroker** [MyHomeMyData/ioBroker.flexcharts#39]
- `<html>` element must have a lang attribute: The <html> element does not have a lang attribute 
-> `<html lang="de">`

- A 'viewport' meta element was not specified. 
   -> `<meta name="viewport" content="width=device-width, initial-scale=1">`

- A 'cache-control' header is missing or empty.

![image](https://github.com/user-attachments/assets/db4419bb-4585-4c09-9ece-1958adbf6037)

**Comment by MyHomeMyData** [comment]
Fixed with version 0.2.0.
