### ISSUE TITLE
Neueste eCharts-Version nutzen?

### ISSUE THREAD

**Issue by mcuiobroker** [MyHomeMyData/ioBroker.flexcharts#40]
Verwendet wird 5.4.3
![image](https://github.com/user-attachments/assets/142d1970-50f0-4ab5-8527-f2bbe6d7dc05)

![image](https://github.com/user-attachments/assets/4efc0d12-a462-4ab6-9d50-6f5d007c0217)

**Comment by MyHomeMyData** [comment]
Update implemented in version 0.2.0
